# Generated by Django 5.2 on 2025-04-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the movie.', max_length=200)),
                ('year', models.IntegerField(help_text='The release year of the movie.')),
                ('length', models.IntegerField(help_text='The length of the movie in minutes.')),
                ('rating', models.FloatField(help_text='The rating of the movie (e.g., IMDb rating).')),
                ('genres', models.JSONField(help_text='A list of genres associated with the movie.')),
                ('age', models.CharField(help_text='The age rating of the movie (e.g., PG-13).', max_length=50)),
                ('directors', models.JSONField(help_text='A list of directors of the movie.')),
                ('writers', models.JSONField(help_text='A list of writers of the movie.')),
                ('actors', models.JSONField(help_text='A list of actors in the movie.')),
            ],
            options={
                'verbose_name_plural': 'Movies',
                'ordering': ['-year', 'name'],
            },
        ),
    ]
