# Generated by Django 5.2 on 2025-04-21 11:56

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieHit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMovies',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the movie.', max_length=200)),
                ('year', models.IntegerField(help_text='The release year of the movie.')),
                ('length', models.IntegerField(help_text='The length of the movie in minutes.')),
                ('rating', models.FloatField(help_text='The rating of the movie (e.g., IMDb rating).')),
                ('genres', models.JSONField(help_text='A list of genres associated with the movie.')),
                ('age', models.CharField(help_text='The age rating of the movie (e.g., PG-13).', max_length=50)),
                ('directors', models.JSONField(help_text='A list of directors of the movie.')),
                ('writers', models.JSONField(help_text='A list of writers of the movie.')),
                ('actors', models.JSONField(help_text='A list of actors in the movie.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical movies',
                'verbose_name_plural': 'historical Movies',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
