# Generated by Django 5.1.7 on 2025-05-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieHit', '0002_historicalmovies'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmovies',
            name='poster',
            field=models.TextField(blank=True, help_text='Upload a poster image for the movie.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='poster',
            field=models.ImageField(blank=True, help_text='Upload a poster image for the movie.', null=True, upload_to='posters/'),
        ),
    ]
