# Generated by Django 5.1.7 on 2025-05-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieHit', '0004_banners_historicalbanners'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='active',
            field=models.BooleanField(default=False, help_text='Is the banner active?'),
        ),
        migrations.AddField(
            model_name='historicalbanners',
            name='active',
            field=models.BooleanField(default=False, help_text='Is the banner active?'),
        ),
    ]
