# Generated by Django 5.1.7 on 2025-05-06 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieHit', '0005_banners_active_historicalbanners_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banners',
            options={'ordering': ['-active', 'name'], 'verbose_name_plural': 'Banners'},
        ),
    ]
