# Generated by Django 5.1.7 on 2025-05-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieHit', '0006_alter_banners_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banners',
            options={'ordering': ['name'], 'verbose_name_plural': 'Banners'},
        ),
        migrations.AddField(
            model_name='historicalmovies',
            name='description',
            field=models.CharField(default='No description', help_text='The description of the movie.', max_length=400),
        ),
        migrations.AddField(
            model_name='historicalmovies',
            name='trailer',
            field=models.URLField(default='No trailer', help_text="The URL of the movie's trailer."),
        ),
        migrations.AddField(
            model_name='movies',
            name='description',
            field=models.CharField(default='No description', help_text='The description of the movie.', max_length=400),
        ),
        migrations.AddField(
            model_name='movies',
            name='trailer',
            field=models.URLField(default='No trailer', help_text="The URL of the movie's trailer."),
        ),
        migrations.AlterField(
            model_name='historicalmovies',
            name='actors',
            field=models.JSONField(default='No actors', help_text='A list of actors in the movie.'),
        ),
        migrations.AlterField(
            model_name='historicalmovies',
            name='age',
            field=models.CharField(default='No age', help_text='The age rating of the movie (e.g., PG-13).', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalmovies',
            name='directors',
            field=models.JSONField(default='No directors', help_text='A list of directors of the movie.'),
        ),
        migrations.AlterField(
            model_name='historicalmovies',
            name='genres',
            field=models.JSONField(default='No genres', help_text='A list of genres associated with the movie.'),
        ),
        migrations.AlterField(
            model_name='historicalmovies',
            name='length',
            field=models.IntegerField(default='No length', help_text='The length of the movie in minutes.'),
        ),
        migrations.AlterField(
            model_name='historicalmovies',
            name='name',
            field=models.CharField(default='No name', help_text='The name of the movie.', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalmovies',
            name='poster',
            field=models.TextField(blank=True, default='No poster', help_text='Upload a poster image for the movie.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmovies',
            name='rating',
            field=models.FloatField(default='No rating', help_text='The rating of the movie (e.g., IMDb rating).'),
        ),
        migrations.AlterField(
            model_name='historicalmovies',
            name='writers',
            field=models.JSONField(default='No writers', help_text='A list of writers of the movie.'),
        ),
        migrations.AlterField(
            model_name='historicalmovies',
            name='year',
            field=models.IntegerField(default='No year', help_text='The release year of the movie.'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='actors',
            field=models.JSONField(default='No actors', help_text='A list of actors in the movie.'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='age',
            field=models.CharField(default='No age', help_text='The age rating of the movie (e.g., PG-13).', max_length=50),
        ),
        migrations.AlterField(
            model_name='movies',
            name='directors',
            field=models.JSONField(default='No directors', help_text='A list of directors of the movie.'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='genres',
            field=models.JSONField(default='No genres', help_text='A list of genres associated with the movie.'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='length',
            field=models.IntegerField(default='No length', help_text='The length of the movie in minutes.'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='name',
            field=models.CharField(default='No name', help_text='The name of the movie.', max_length=200),
        ),
        migrations.AlterField(
            model_name='movies',
            name='poster',
            field=models.ImageField(blank=True, default='No poster', help_text='Upload a poster image for the movie.', null=True, upload_to='posters/'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='rating',
            field=models.FloatField(default='No rating', help_text='The rating of the movie (e.g., IMDb rating).'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='writers',
            field=models.JSONField(default='No writers', help_text='A list of writers of the movie.'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='year',
            field=models.IntegerField(default='No year', help_text='The release year of the movie.'),
        ),
    ]
