# Generated by Django 5.1.7 on 2025-05-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieHit', '0007_alter_banners_options_historicalmovies_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmovies',
            name='unique_id',
            field=models.CharField(blank=True, db_index=True, help_text='Unique YouTube-like ID for the movie URL', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='movies',
            name='unique_id',
            field=models.CharField(blank=True, help_text='Unique YouTube-like ID for the movie URL', max_length=15, null=True, unique=True),
        ),
    ]
