# Generated by Django 5.1.7 on 2025-05-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieHit', '0008_historicalmovies_unique_id_movies_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmovies',
            name='actors',
            field=models.JSONField(default=['No actors'], help_text='A list of actors in the movie.'),
        ),
        migrations.AlterField(
            model_name='historicalmovies',
            name='directors',
            field=models.JSONField(default=['No directors'], help_text='A list of directors of the movie.'),
        ),
        migrations.AlterField(
            model_name='historicalmovies',
            name='genres',
            field=models.JSONField(default=['No genres'], help_text='A list of genres associated with the movie.'),
        ),
        migrations.AlterField(
            model_name='historicalmovies',
            name='unique_id',
            field=models.CharField(blank=True, db_index=True, help_text='Unique ID for the movie URL', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmovies',
            name='writers',
            field=models.JSONField(default=['No writers'], help_text='A list of writers of the movie.'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='actors',
            field=models.JSONField(default=['No actors'], help_text='A list of actors in the movie.'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='directors',
            field=models.JSONField(default=['No directors'], help_text='A list of directors of the movie.'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='genres',
            field=models.JSONField(default=['No genres'], help_text='A list of genres associated with the movie.'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='unique_id',
            field=models.CharField(blank=True, help_text='Unique ID for the movie URL', max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='writers',
            field=models.JSONField(default=['No writers'], help_text='A list of writers of the movie.'),
        ),
    ]
