# Generated by Django 5.1.7 on 2025-05-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieHit', '0010_alter_historicalmovies_actors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmovies',
            name='actors',
            field=models.JSONField(default={' ': 'n', 'N': 'n', 'a': 'e', 'o': 'o'}, help_text='A list of actors in the movie.'),
        ),
        migrations.AlterField(
            model_name='historicalmovies',
            name='directors',
            field=models.JSONField(default={' ': 'n', 'N': 'n', 'd': 'e', 'o': 'o'}, help_text='A list of directors of the movie.'),
        ),
        migrations.AlterField(
            model_name='historicalmovies',
            name='genres',
            field=models.JSONField(default={' ': 'n', 'N': 'n', 'g': 'e', 'o': 'o'}, help_text='A list of genres associated with the movie.'),
        ),
        migrations.AlterField(
            model_name='historicalmovies',
            name='writers',
            field=models.JSONField(default={' ': 'n', 'N': 'n', 'o': 'o', 'w': 'e'}, help_text='A list of writers of the movie.'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='actors',
            field=models.JSONField(default={' ': 'n', 'N': 'n', 'a': 'e', 'o': 'o'}, help_text='A list of actors in the movie.'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='directors',
            field=models.JSONField(default={' ': 'n', 'N': 'n', 'd': 'e', 'o': 'o'}, help_text='A list of directors of the movie.'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='genres',
            field=models.JSONField(default={' ': 'n', 'N': 'n', 'g': 'e', 'o': 'o'}, help_text='A list of genres associated with the movie.'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='writers',
            field=models.JSONField(default={' ': 'n', 'N': 'n', 'o': 'o', 'w': 'e'}, help_text='A list of writers of the movie.'),
        ),
    ]
